from config import db
from datetime import datetime


class ChatLogs(db.Model):
    __tablename__ = 'chat_logs'

    id = db.Column(db.Integer, primary_key=True)
    prompt = db.Column(db.Text, nullable=False)          # Prompt provided by the user
    completion = db.Column(db.Text, nullable=False)      # Completion generated by OpenAI
    timestamp = db.Column(db.DateTime, default=datetime.utcnow())  # Timestamp of the log entry
    user_id = db.Column(db.String(50), db.ForeignKey('users.id'), nullable=False)  # Reference the user_id from users table
